INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cannabis');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'abuse');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'crack');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'drunk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'grass');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), '4r5e');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), '5h1t');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), '5hit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'a55');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'anal');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'anus');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ar5e');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'arrse');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'arse');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ass');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ass-fucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'asses');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'assfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'assfukka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'asshole');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'assholes');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'asswhole');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'a_s_s');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'b!tch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'b00bs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'b17ch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'b1tch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ballbag');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'balls');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ballsack');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bastard');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'beastial');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'beastiality');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bellend');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bestial');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bestiality');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bi+ch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'biatch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bitch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bitcher');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bitchers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bitches');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bitchin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bitching');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bloody');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'blow job');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'blowjob');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'blowjobs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'boiolas');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bollock');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bollok');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'boner');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'boob');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'boobs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'booobs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'boooobs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'booooobs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'booooooobs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'breasts');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'buceta');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bugger');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bum');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'bunny fucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'butt');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'butthole');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'buttmuch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'buttplug');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'c0ck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'c0cksucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'carpet muncher');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cawk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'chink');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cipa');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cl1t');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'clit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'clitoris');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'clits');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cnut');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cock');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cock-sucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cockface');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cockhead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cockmunch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cockmuncher');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksuck ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksucked ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksucking');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksucks ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksuka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cocksukka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cok');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cokmuncher');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'coksucka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'coon');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cox');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'crap');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cum');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cummer');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cumming');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cums');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cumshot');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cunilingus');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cunillingus');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cunnilingus');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cunt');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cuntlick ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cuntlicker ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cuntlicking ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cunts');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyalis');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyberfuc');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyberfuck ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyberfucked ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyberfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyberfuckers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'cyberfucking ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'd1ck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'damn');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dick');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dickhead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dildo');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dildos');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dink');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dinks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dirsa');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dlck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dog-fucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'doggin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dogging');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'donkeyribber');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'doosh');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'duche');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'dyke');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejaculate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejaculated');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejaculates ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejaculating ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejaculatings');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejaculation');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ejakulate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'f u c k');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'f u c k e r');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'f4nny');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fag');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fagging');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'faggitt');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'faggot');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'faggs');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fagot');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fagots');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fags');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fanny');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fannyflaps');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fannyfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fanyy');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fatass');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fcuk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fcuker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fcuking');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'feck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fecker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'felching');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fellate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fellatio');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fingerfuck ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fingerfucked ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fingerfucker ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fingerfuckers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fingerfucking ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fingerfucks ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfucked ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfucker ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfuckers ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfucking ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfuckings ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fistfucks ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'flange');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fook');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fooker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fucka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fucked');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckhead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckheads');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fucking');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckings');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckingshitmotherfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckme ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fucks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckwhit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuckwit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fudge packer');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fudgepacker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fukker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fukkin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fuks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fukwhit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fukwit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fux');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'fux0r');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'f_u_c_k');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'gangbang');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'gangbanged ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'gangbangs ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'gaylord');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'gaysex');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'goatse');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'God');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'god-dam');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'god-damned');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'goddamn');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'goddamned');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hardcoresex ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hell');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'heshe');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hoar');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hoare');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hoer');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'homo');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hore');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'horniest');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'horny');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'hotsex');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jack-off ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jackoff');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jap');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jerk-off ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jism');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jiz ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jizm ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'jizz');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kawk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knob');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knobead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knobed');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knobend');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knobhead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knobjocky');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'knobjokey');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kock');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kondum');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kondums');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kum');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kummer');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kumming');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kums');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'kunilingus');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'l3i+ch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'l3itch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'labia');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'lmfao');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'lust');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'lusting');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'm0f0');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'm0fo');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'm45terbate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ma5terb8');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'ma5terbate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masochist');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'master-bate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masterb8');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masterbat*');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masterbat3');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masterbate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masterbation');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masterbations');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'masturbate');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mo-fo');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mof0');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mofo');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafucka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafuckas');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafuckaz');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafucked ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafuckers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafuckin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafucking ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafuckings');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mothafucks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mother fucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfucked');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfuckers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfuckin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfucking');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfuckings');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfuckka');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'motherfucks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'muff');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mutha');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'muthafecker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'muthafuckker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'muther');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'mutherfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'n1gga');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'n1gger');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nazi');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nigg3r');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nigg4h');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nigga');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'niggah');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'niggas');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'niggaz');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nigger');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'niggers ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nob');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nob jokey');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nobhead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nobjocky');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nobjokey');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'numbnuts');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'nutsack');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'orgasim ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'orgasims ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'orgasm');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'orgasms ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'p0rn');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pawn');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pecker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'penis');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'penisfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phonesex');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phuk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phuked');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phuking');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phukked');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phukking');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phuks');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'phuq');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pigfucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pimpis');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'piss');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pissed');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pisser');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pissers');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pisses ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pissflaps');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pissin ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pissing');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pissoff ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'poop');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'porn');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'porno');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pornography');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pornos');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'prick');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pricks ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pron');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pube');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pusse');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pussi');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pussies');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pussy');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'pussys ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'rectum');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'retard');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'rimjaw');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'rimming');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 's hit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 's.o.b.');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'sadist');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'schlong');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'screwing');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'scroat');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'scrote');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'scrotum');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'semen');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'sex');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'sh!+');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'sh!t');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'sh1t');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shag');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shagger');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shaggin');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shagging');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shemale');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shi+');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitdick');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shite');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shited');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitey');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitfuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitfull');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shithead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shiting');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitings');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shits');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitted');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitter');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitters ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitting');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shittings');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'shitty ');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'skank');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'slut');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'sluts');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'smegma');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'smut');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'snatch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'son-of-a-bitch');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'spac');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'spunk');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 's_h_i_t');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 't1tt1e5');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 't1tties');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'teets');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'teez');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'testical');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'testicle');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tit');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'titfuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tits');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'titt');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tittie5');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tittiefucker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'titties');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tittyfuck');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tittywank');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'titwank');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tosser');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'turd');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'tw4t');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'twat');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'twathead');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'twatty');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'twunt');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'twunter');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'v14gra');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'v1gra');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'vagina');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'viagra');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'vulva');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'w00se');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'wang');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'wank');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'wanker');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'wanky');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'whoar');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'whore');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'willies');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'willy');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'xrated');
INSERT INTO public.restrictedword(id, restrictedword) VALUES (nextval ('hibernate_sequence'), 'xxx');
